export const FETCH_STORE_DATA_SUCCESS = "FETCH_STORE_DATA_SUCCESS";
export const UPDATE_STORE_IS_ACTIVE_SUCCESS = "UPDATE_STORE_IS_ACTIVE_SUCCESS";
export const SET_STORE_IS_EDITING = "SET_STORE_IS_EDITING";
export const SET_STORE_IS_EDITING_UPDATED = "SET_STORE_IS_EDITING_UPDATED";
